class RegisterListData {
  RegisterListData({
    this.imagePath = '',
    this.titleTxt = '',
    this.subTxt = "",
    this.dist = '',
    this.reviews = 80,
    this.rating = 4.5,
    this.perNight = 180,
  });

  String imagePath;
  String titleTxt;
  String subTxt;
  String dist;
  double rating;
  int reviews;
  int perNight;

  List<String> courses = [
    'Communications',
    'Network Lab',
    'Communications Lab',
    'C++',
    'Java',
    'Algorithms',
    'Data structure',
    'Architecture 1',
    'Network 1',
    'Architecture 2',
    'Network 2',
    'Parallel Computing',
    'Image Processing',
    'Digital 1',
    'Digital 2',
    'Digital 3'
  ];

  static List<RegisterListData> hotelList = <RegisterListData>[
    RegisterListData(
      imagePath: 'assets/logo1.jpg',
      titleTxt: 'Communications',
      subTxt: '8 - 9',
      dist: 'Sun Tue Thu',
      reviews: 80,
      rating: 4.4,
      perNight: 180,
    ),
    RegisterListData(
      imagePath: 'assets/logo1.jpg',
      titleTxt: 'Network Lab',
      subTxt: '11 - 2',
      dist: 'Tue',
      reviews: 74,
      rating: 4.5,
      perNight: 200,
    ),
    RegisterListData(
      imagePath: 'assets/logo1.jpg',
      titleTxt: 'Communications Lab',
      subTxt: '2 - 5',
      dist: 'Thu',
      reviews: 62,
      rating: 4.0,
      perNight: 60,
    ),
    RegisterListData(
      imagePath: 'assets/logo1.jpg',
      titleTxt: 'C++',
      subTxt: '10 - 11',
      dist: 'Sun Tue Thu',
      reviews: 90,
      rating: 4.4,
      perNight: 170,
    ),
    RegisterListData(
      imagePath: 'assets/logo1.jpg',
      titleTxt: 'Java',
      subTxt: '9 - 10',
      dist: 'Sun Tue Thu',
      reviews: 240,
      rating: 4.5,
      perNight: 200,
    ),
    RegisterListData(
      imagePath: 'assets/logo1.jpg',
      titleTxt: 'Algorithms',
      subTxt: '9 - 10',
      dist: 'Sun Tue Thu',
      reviews: 240,
      rating: 4.5,
      perNight: 200,
    ),
    RegisterListData(
      imagePath: 'assets/logo1.jpg',
      titleTxt: 'Data structure',
      subTxt: '8 - 9.30',
      dist: 'Mon Wed',
      reviews: 240,
      rating: 4.5,
      perNight: 200,
    ),
    RegisterListData(
      imagePath: 'assets/logo1.jpg',
      titleTxt: 'Architecture 1',
      subTxt: '9.30 - 11',
      dist: 'Mon Wed',
      reviews: 240,
      rating: 4.5,
      perNight: 200,
    ),
    RegisterListData(
      imagePath: 'assets/logo1.jpg',
      titleTxt: 'Network 1',
      subTxt: '11 - 12',
      dist: 'Sun Tue Thu',
      reviews: 240,
      rating: 4.5,
      perNight: 200,
    ),
    RegisterListData(
      imagePath: 'assets/logo1.jpg',
      titleTxt: 'Architecture 2',
      subTxt: '1 - 2',
      dist: 'Sun Tue Thu',
      reviews: 240,
      rating: 4.5,
      perNight: 200,
    ),
    RegisterListData(
      imagePath: 'assets/logo1.jpg',
      titleTxt: 'Network 2',
      subTxt: '2 - 3',
      dist: 'Sun Tue Thu',
      reviews: 240,
      rating: 4.5,
      perNight: 200,
    ),
    RegisterListData(
      imagePath: 'assets/logo1.jpg',
      titleTxt: 'Parallel Computing',
      subTxt: '9 - 10',
      dist: 'Sun Tue Thu',
      reviews: 240,
      rating: 4.5,
      perNight: 200,
    ),
    RegisterListData(
      imagePath: 'assets/logo1.jpg',
      titleTxt: '11 - 12',
      subTxt: 'Wembley, London',
      dist: 'Sun Tue Thu',
      reviews: 240,
      rating: 4.5,
      perNight: 200,
    ),
    RegisterListData(
      imagePath: 'assets/logo1.jpg',
      titleTxt: 'Digital 1',
      subTxt: '1.30 - 3',
      dist: 'Mon Wed',
      reviews: 240,
      rating: 4.5,
      perNight: 200,
    ),
    RegisterListData(
      imagePath: 'assets/logo1.jpg',
      titleTxt: 'Digital 2',
      subTxt: '11 - 12.30',
      dist: 'Mon Wed',
      reviews: 240,
      rating: 4.5,
      perNight: 200,
    ),
    RegisterListData(
      imagePath: 'assets/logo1.jpg',
      titleTxt: 'Digital 3',
      subTxt: '1 - 2',
      dist: 'Sun Tue Thu',
      reviews: 240,
      rating: 4.5,
      perNight: 200,
    ),
  ];
}
